import Head from 'next/head';
import Image from 'next/image';
import Categories from './categories';
import Shop from './shop';

export default function Home() {
	return (
		<div>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<main className=' container mx-auto bg-gray-200 p-8  '>
				<Categories />
				<Shop />
			</main>
		</div>
	);
}
