import Head from 'next/head';
import Image from 'next/image';
import Categories from './categories';
import Shop from './shop';

export default function Home() {
	return (
		<div className='w-screen min-h-screen p-3 bg-slate-100'>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<main className=' prose-xl text-gray-700    font-openSans prose-headings:font-semibold scroll-smooth container mx-auto heading:tracking-wider leading-6 '>
				<Categories />
				<Shop />
			</main>
		</div>
	);
}
