import Head from 'next/head';
import Image from 'next/image';
import Categories from './categories';
import Shop from './shop';

export default function Home() {
	const utilities = {
		h1: 'text-8xl',
		h2: 'text-5xl',
		h3: 'text-4xl',
		h5: 'text-3xl',
	};
	return (
		<div className='w-screen min-h-screen p-3 bg-slate-100'>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<main className=' prose-xl text-gray-700    font-openSans prose-headings:font-semibold scroll-smooth container mx-auto '>
				<Categories />
				<Shop />
			</main>
		</div>
	);
}
